export const TOPICS = [
  { category: 'Python', color: '#3b82f6', items: [
    { id: '01', label: 'Python Basics', file: '01_Python_Basic_Questions.md', questions: 24, icon: '🐍' },
    { id: '02', label: 'Python Intermediate', file: '02_Python_Intermediate_Questions.md', questions: 22, icon: '🐍' },
    { id: '03', label: 'Python Advanced', file: '03_Python_Advanced_Questions.md', questions: 20, icon: '🐍' },
    { id: '04', label: 'Python SDET-Specific', file: '04_Python_SDET_Specific_Questions.md', questions: 20, icon: '🧪' },
    { id: '05', label: 'Python Coding Problems', file: '05_Python_Coding_Problems.md', questions: 50, icon: '💻' },
  ]},
  { category: 'Core QA & Process', color: '#10b981', items: [
    { id: '07', label: 'Agile / SDLC / Framework', file: '07_Review_Agile_SDLC_Framework.md', questions: 20, icon: '📋' },
  ]},
  { category: 'SQL & Database', color: '#f59e0b', items: [
    { id: '08', label: 'SQL Interview Questions', file: '08_Review_SQL_Questions.md', questions: 25, icon: '🗃️' },
    { id: '16', label: 'SQL Coding Problems', file: '16_Additional_SQL_Coding.md', questions: 25, icon: '📊' },
  ]},
  { category: 'Selenium & UI', color: '#ef4444', items: [
    { id: '09', label: 'Selenium / TestNG / Jenkins', file: '09_Review_Selenium_TestNG_Jenkins.md', questions: 33, icon: '🌐' },
  ]},
  { category: 'API Testing', color: '#8b5cf6', items: [
    { id: '10', label: 'REST Assured / API', file: '10_Review_REST_Assured_API.md', questions: 19, icon: '🔌' },
  ]},
  { category: 'Java & OOP', color: '#ec4899', items: [
    { id: '11', label: 'Java OOP Concepts', file: '11_Review_Java_OOP.md', questions: 24, icon: '☕' },
    { id: '13', label: 'Java Coding Problems', file: '13_Java_Coding_Problems.md', questions: 38, icon: '💻' },
  ]},
  { category: 'Advanced Topics', color: '#06b6d4', items: [
    { id: '14', label: 'Scenario-Based Questions', file: '14_Scenario_Based_Questions.md', questions: 20, icon: '🎯' },
    { id: '15', label: 'Framework / Git / DevOps', file: '15_Framework_Git_Maven_DevOps.md', questions: 15, icon: '⚙️' },
  ]},
  { category: 'Modern Testing 2026', color: '#14b8a6', items: [
    { id: '17', label: 'AI in Testing', file: '17_AI_Testing_Interview_Questions.md', questions: 23, icon: '🤖' },
    { id: '18', label: 'Playwright', file: '18_Playwright_Interview_Questions.md', questions: 26, icon: '🎭' },
  ]},
  { category: 'Profile', color: '#6366f1', items: [
    { id: '06', label: 'LinkedIn Profile Review', file: '06_LinkedIn_Profile_Review.md', questions: 0, icon: '👤' },
  ]},
]

export const ALL_ITEMS = TOPICS.flatMap(g => g.items)
export const TOTAL_QUESTIONS = ALL_ITEMS.reduce((sum, i) => sum + i.questions, 0)

export const ROADMAP = [
  { phase: 'Foundation', days: '1-7', color: '#3b82f6', description: 'Build your core knowledge base',
    items: [
      { day: 1, title: 'Python Basics', topicId: '01', tasks: ['Read Python Basic Questions', 'Take Python Basics Quiz', 'Solve 3 coding problems'] },
      { day: 2, title: 'Python Intermediate', topicId: '02', tasks: ['Read OOP, Decorators, Generators', 'Practice class inheritance', 'Solve 3 coding problems'] },
      { day: 3, title: 'Python Advanced', topicId: '03', tasks: ['Read Metaclasses, GIL, Async', 'Study Design Patterns', 'Solve 3 coding problems'] },
      { day: 4, title: 'SQL Fundamentals', topicId: '08', tasks: ['Read SQL Interview Questions', 'Practice JOINs and GROUP BY', 'Take SQL Quiz'] },
      { day: 5, title: 'SQL Coding', topicId: '16', tasks: ['Solve Nth highest salary', 'Practice window functions', 'Solve 5 SQL problems'] },
      { day: 6, title: 'Java OOP', topicId: '11', tasks: ['Read 4 pillars of OOP', 'Study Collections Framework', 'Practice Java 8 features'] },
      { day: 7, title: 'Review & Quiz', topicId: null, tasks: ['Review all Week 1 topics', 'Take mixed quiz', 'Identify weak areas'] },
    ]},
  { phase: 'Core Skills', days: '8-14', color: '#10b981', description: 'Master testing tools and frameworks',
    items: [
      { day: 8, title: 'Selenium WebDriver', topicId: '09', tasks: ['Read Selenium questions', 'Study waits and locators', 'Take Selenium Quiz'] },
      { day: 9, title: 'TestNG & Jenkins', topicId: '09', tasks: ['Study TestNG annotations', 'Learn Jenkins pipeline', 'Practice testng.xml'] },
      { day: 10, title: 'REST API Testing', topicId: '10', tasks: ['Read REST Assured questions', 'Study HTTP methods & status codes', 'Take API Quiz'] },
      { day: 11, title: 'Python SDET Skills', topicId: '04', tasks: ['Read pytest & fixtures', 'Study mocking & API testing', 'Solve SDET problems'] },
      { day: 12, title: 'Java Coding Day 1', topicId: '13', tasks: ['Solve string problems', 'Solve number problems', 'Practice 8 problems'] },
      { day: 13, title: 'Java Coding Day 2', topicId: '13', tasks: ['Solve array problems', 'Practice sorting algorithms', 'Practice 8 problems'] },
      { day: 14, title: 'Week 2 Review', topicId: null, tasks: ['Review all Week 2 topics', 'Take mixed quiz', 'Time yourself on problems'] },
    ]},
  { phase: 'Advanced', days: '15-21', color: '#f59e0b', description: 'Level up with modern tools & scenarios',
    items: [
      { day: 15, title: 'Framework Architecture', topicId: '15', tasks: ['Study POM & hybrid framework', 'Learn Maven lifecycle', 'Understand CI/CD'] },
      { day: 16, title: 'Git & DevOps', topicId: '15', tasks: ['Practice Git commands', 'Study branching strategies', 'Learn Docker basics'] },
      { day: 17, title: 'Playwright', topicId: '18', tasks: ['Read Playwright questions', 'Compare with Selenium', 'Study auto-waiting'] },
      { day: 18, title: 'AI in Testing', topicId: '17', tasks: ['Read AI testing questions', 'Study AI tools for QA', 'Take AI Quiz'] },
      { day: 19, title: 'Agile & SDLC', topicId: '07', tasks: ['Read Agile questions', 'Study Sprint ceremonies', 'Practice scenario answers'] },
      { day: 20, title: 'Python Coding Sprint', topicId: '05', tasks: ['Solve 10 Python problems', 'Focus on arrays & strings', 'Time each solution'] },
      { day: 21, title: 'Week 3 Review', topicId: null, tasks: ['Review all Week 3 topics', 'Take full mixed quiz', 'Record weak spots'] },
    ]},
  { phase: 'Interview Ready', days: '22-30', color: '#ef4444', description: 'Polish, practice, and ace it!',
    items: [
      { day: 22, title: 'Scenario Questions', topicId: '14', tasks: ['Study scenario-based Q&A', 'Practice answering aloud', 'Time your responses'] },
      { day: 23, title: 'Mock Interview 1', topicId: null, tasks: ['Python + SQL mock (45 min)', 'Review your answers', 'Note improvements'] },
      { day: 24, title: 'Mock Interview 2', topicId: null, tasks: ['Selenium + API mock (45 min)', 'Review your answers', 'Focus on weak areas'] },
      { day: 25, title: 'Coding Marathon', topicId: null, tasks: ['Solve 15 mixed problems', 'Practice under time pressure', '2 min per easy, 5 min per medium'] },
      { day: 26, title: 'Framework Deep Dive', topicId: null, tasks: ['Explain your framework verbally', 'Draw architecture diagram', 'Practice whiteboard'] },
      { day: 27, title: 'Full Mock Interview', topicId: null, tasks: ['Complete 60 min mock', 'Cover all topics', 'Record and review'] },
      { day: 28, title: 'Weak Area Focus', topicId: null, tasks: ['Revisit lowest quiz scores', 'Re-read weak chapters', 'Retake failed quizzes'] },
      { day: 29, title: 'Speed Round', topicId: null, tasks: ['Quick-fire 50 questions', '30 seconds each', 'Rapid recall practice'] },
      { day: 30, title: 'Final Review', topicId: null, tasks: ['Skim all chapters', 'Review all badges earned', 'You are READY! 🎉'] },
    ]},
]

export const QUIZZES = {
  python: {
    title: 'Python Fundamentals',
    icon: '🐍',
    questions: [
      { q: 'What is the output of `type([]) is list`?', options: ['True', 'False', 'TypeError', 'None'], answer: 0 },
      { q: 'Which keyword is used to create a generator?', options: ['return', 'yield', 'generate', 'async'], answer: 1 },
      { q: 'What does GIL stand for?', options: ['Global Import Lock', 'Global Interpreter Lock', 'General Input Loop', 'Generic Interface Layer'], answer: 1 },
      { q: '`is` vs `==` — `is` checks:', options: ['Value equality', 'Type equality', 'Identity (same object)', 'None of these'], answer: 2 },
      { q: 'Output of `bool([])`?', options: ['True', 'False', 'None', 'Error'], answer: 1 },
      { q: 'What does `@staticmethod` mean?', options: ['Method accesses class', 'Method accesses instance', 'Method needs no self/cls', 'Method is private'], answer: 2 },
      { q: 'Which is immutable?', options: ['list', 'dict', 'set', 'tuple'], answer: 3 },
      { q: 'Output of `[1,2] + [3,4]`?', options: ['[1,2,3,4]', '[[1,2],[3,4]]', '[4,6]', 'Error'], answer: 0 },
      { q: 'Deep copy vs shallow copy?', options: ['Same thing', 'Deep copies nested objects too', 'Shallow copies nested objects', 'Deep is faster'], answer: 1 },
      { q: 'What is a decorator?', options: ['A class method', 'A function that wraps another function', 'A type of variable', 'A loop construct'], answer: 1 },
    ]
  },
  sql: {
    title: 'SQL Mastery',
    icon: '🗃️',
    questions: [
      { q: 'WHERE vs HAVING?', options: ['Same thing', 'WHERE filters rows, HAVING filters groups', 'HAVING filters rows, WHERE filters groups', 'WHERE is faster'], answer: 1 },
      { q: 'RANK() vs DENSE_RANK()?', options: ['Same behavior', 'RANK skips numbers after ties', 'DENSE_RANK skips numbers', 'Neither handles ties'], answer: 1 },
      { q: 'What does COALESCE do?', options: ['Joins tables', 'Returns first non-NULL value', 'Counts rows', 'Groups data'], answer: 1 },
      { q: 'Which JOIN returns all rows from both tables?', options: ['INNER JOIN', 'LEFT JOIN', 'FULL OUTER JOIN', 'CROSS JOIN'], answer: 2 },
      { q: 'DELETE vs TRUNCATE?', options: ['Same thing', 'DELETE is logged, TRUNCATE is not', 'TRUNCATE can have WHERE', 'DELETE is faster'], answer: 1 },
      { q: 'What is a CTE?', options: ['Column Type Expression', 'Common Table Expression', 'Create Table Entity', 'Conditional Test Eval'], answer: 1 },
      { q: 'Can you use WHERE with aggregate functions?', options: ['Yes', 'No, use HAVING', 'Only with COUNT', 'Only in subqueries'], answer: 1 },
      { q: 'CROSS JOIN produces?', options: ['Matching rows only', 'Cartesian product', 'NULL rows', 'Distinct rows'], answer: 1 },
    ]
  },
  selenium: {
    title: 'Selenium & TestNG',
    icon: '🌐',
    questions: [
      { q: 'Implicit wait vs Explicit wait?', options: ['Same thing', 'Implicit is global timeout, Explicit is condition-based', 'Explicit is global', 'Neither exists'], answer: 1 },
      { q: 'How to handle alerts in Selenium?', options: ['driver.findElement()', 'driver.switchTo().alert()', 'driver.getAlert()', 'driver.handleAlert()'], answer: 1 },
      { q: 'What is StaleElementReferenceException?', options: ['Element not found', 'Element no longer in DOM', 'Page not loaded', 'Wrong locator'], answer: 1 },
      { q: 'CSS Selector vs XPath — which is generally faster?', options: ['XPath', 'CSS Selector', 'Same speed', 'Depends on browser'], answer: 1 },
      { q: 'What is Page Object Model?', options: ['A testing framework', 'Design pattern — each page is a class', 'A Selenium plugin', 'A CI/CD tool'], answer: 1 },
      { q: 'TestNG @BeforeMethod runs:', options: ['Once before all tests', 'Before each test method', 'After each test', 'Only on failure'], answer: 1 },
      { q: 'How to take screenshot in Selenium?', options: ['driver.screenshot()', '((TakesScreenshot)driver).getScreenshotAs()', 'driver.capture()', 'WebElement.screenshot()'], answer: 1 },
      { q: 'What does `driver.manage().window().maximize()` do?', options: ['Minimizes window', 'Maximizes browser window', 'Closes window', 'Resizes to 800x600'], answer: 1 },
    ]
  },
  api: {
    title: 'API Testing',
    icon: '🔌',
    questions: [
      { q: 'PUT vs PATCH?', options: ['Same thing', 'PUT replaces entire resource, PATCH updates partially', 'PATCH replaces, PUT updates', 'PUT is for creation'], answer: 1 },
      { q: 'HTTP 201 status means?', options: ['OK', 'Created', 'Accepted', 'No Content'], answer: 1 },
      { q: 'What is idempotent?', options: ['Fast request', 'Same request = same result always', 'One-time request', 'Async request'], answer: 1 },
      { q: 'Authentication vs Authorization?', options: ['Same thing', 'Auth = who you are, Authz = what you can do', 'Auth = permissions, Authz = identity', 'Neither is needed'], answer: 1 },
      { q: 'Status 429 means?', options: ['Not Found', 'Server Error', 'Too Many Requests', 'Unauthorized'], answer: 2 },
      { q: 'REST Assured uses which syntax?', options: ['Arrange-Act-Assert', 'Given-When-Then (BDD)', 'Setup-Execute-Verify', 'Before-After'], answer: 1 },
      { q: 'JSON Schema validation ensures?', options: ['Data values are correct', 'Response structure matches expected format', 'API is fast', 'Authentication works'], answer: 1 },
      { q: 'Which HTTP method is NOT idempotent?', options: ['GET', 'PUT', 'POST', 'DELETE'], answer: 2 },
    ]
  },
  java: {
    title: 'Java & OOP',
    icon: '☕',
    questions: [
      { q: '`==` vs `.equals()` for String?', options: ['Same thing', '== checks reference, .equals() checks value', '== checks value, .equals() checks reference', 'Neither works'], answer: 1 },
      { q: 'Can you override a static method?', options: ['Yes', 'No, static methods are hidden', 'Only in interfaces', 'Only with @Override'], answer: 1 },
      { q: 'Default value of int instance variable?', options: ['null', '0', '-1', 'undefined'], answer: 1 },
      { q: 'What is method overloading?', options: ['Same name, same params', 'Same name, different params', 'Different name, same params', 'Inheritance required'], answer: 1 },
      { q: 'Which collection allows no duplicates?', options: ['List', 'ArrayList', 'Set', 'Queue'], answer: 2 },
      { q: 'What is Singleton pattern?', options: ['Many instances', 'Exactly one instance of a class', 'Factory method', 'Observer pattern'], answer: 1 },
      { q: 'abstract class vs interface?', options: ['Same thing', 'Abstract can have state, interface cannot (pre-Java 8)', 'Interface can have constructors', 'Abstract has no methods'], answer: 1 },
      { q: 'What does `final` mean for a variable?', options: ['It can change once', 'It cannot be reassigned', 'It is null', 'It is static'], answer: 1 },
    ]
  },
  framework: {
    title: 'Framework & DevOps',
    icon: '⚙️',
    questions: [
      { q: 'What does CI stand for?', options: ['Code Integration', 'Continuous Integration', 'Complete Installation', 'Central Interface'], answer: 1 },
      { q: '`mvn clean test` does what?', options: ['Only cleans', 'Cleans target/ then runs tests', 'Only runs tests', 'Deploys to production'], answer: 1 },
      { q: 'Git `rebase` vs `merge`?', options: ['Same thing', 'Rebase rewrites history, merge preserves it', 'Merge rewrites history', 'Rebase creates merge commit'], answer: 1 },
      { q: 'What is Docker used for in testing?', options: ['Code editing', 'Consistent test environments via containers', 'Database management', 'Report generation'], answer: 1 },
      { q: 'Cucumber connects features to code via?', options: ['pom.xml', 'TestRunner with @CucumberOptions', 'Jenkins', 'Docker'], answer: 1 },
      { q: 'Smoke test vs Regression test?', options: ['Same scope', 'Smoke is broad+shallow, Regression is broad+deep', 'Regression is shallow', 'Smoke takes longer'], answer: 1 },
      { q: '`git stash` does what?', options: ['Deletes changes', 'Saves uncommitted changes temporarily', 'Commits changes', 'Creates branch'], answer: 1 },
      { q: 'Maven lifecycle — which runs first?', options: ['test', 'compile', 'validate', 'package'], answer: 2 },
    ]
  },
}

export const PRACTICE_PROBLEMS = [
  { id: 'p1', title: 'Reverse a String', difficulty: 'Easy', category: 'String', language: 'python',
    description: 'Write a function that reverses a given string without using built-in reverse methods.',
    examples: [{ input: '"hello"', output: '"olleh"' }, { input: '"Python"', output: '"nohtyP"' }],
    hint: 'Try using string slicing or two-pointer approach.',
    solution: `def reverse_string(s):\n    return s[::-1]\n\n# Alternative: two-pointer\ndef reverse_string_manual(s):\n    chars = list(s)\n    left, right = 0, len(chars) - 1\n    while left < right:\n        chars[left], chars[right] = chars[right], chars[left]\n        left += 1\n        right -= 1\n    return ''.join(chars)`,
  },
  { id: 'p2', title: 'Two Sum', difficulty: 'Easy', category: 'Array', language: 'python',
    description: 'Given an array of integers and a target, return indices of two numbers that add up to the target.',
    examples: [{ input: 'nums=[2,7,11,15], target=9', output: '[0, 1]' }],
    hint: 'Use a hashmap to store complement values.',
    solution: `def two_sum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in seen:\n            return [seen[complement], i]\n        seen[num] = i\n    return []`,
  },
  { id: 'p3', title: 'FizzBuzz', difficulty: 'Easy', category: 'Logic', language: 'python',
    description: 'Print numbers 1-n. For multiples of 3 print "Fizz", multiples of 5 print "Buzz", both print "FizzBuzz".',
    examples: [{ input: 'n=15', output: '1,2,Fizz,4,Buzz,...,FizzBuzz' }],
    hint: 'Check divisibility by 15 first, then 3, then 5.',
    solution: `def fizzbuzz(n):\n    result = []\n    for i in range(1, n + 1):\n        if i % 15 == 0:\n            result.append("FizzBuzz")\n        elif i % 3 == 0:\n            result.append("Fizz")\n        elif i % 5 == 0:\n            result.append("Buzz")\n        else:\n            result.append(str(i))\n    return result`,
  },
  { id: 'p4', title: 'Check Palindrome', difficulty: 'Easy', category: 'String', language: 'python',
    description: 'Check if a given string is a palindrome (reads same forwards and backwards).',
    examples: [{ input: '"racecar"', output: 'True' }, { input: '"hello"', output: 'False' }],
    hint: 'Compare string with its reverse, or use two pointers.',
    solution: `def is_palindrome(s):\n    s = s.lower()\n    return s == s[::-1]\n\n# Two-pointer approach\ndef is_palindrome_v2(s):\n    s = s.lower()\n    left, right = 0, len(s) - 1\n    while left < right:\n        if s[left] != s[right]:\n            return False\n        left += 1\n        right -= 1\n    return True`,
  },
  { id: 'p5', title: 'Find Duplicates in Array', difficulty: 'Easy', category: 'Array', language: 'python',
    description: 'Find all duplicate elements in a given array.',
    examples: [{ input: '[1,2,3,2,4,3]', output: '[2, 3]' }],
    hint: 'Use a set to track seen elements.',
    solution: `def find_duplicates(arr):\n    seen = set()\n    duplicates = set()\n    for num in arr:\n        if num in seen:\n            duplicates.add(num)\n        seen.add(num)\n    return list(duplicates)`,
  },
  { id: 'p6', title: 'Nth Highest Salary (SQL)', difficulty: 'Medium', category: 'SQL', language: 'sql',
    description: 'Write a SQL query to find the Nth highest salary from an employees table.',
    examples: [{ input: 'N=3', output: '3rd highest salary value' }],
    hint: 'Use DENSE_RANK() window function or LIMIT+OFFSET.',
    solution: `-- Method 1: DENSE_RANK\nSELECT salary FROM (\n    SELECT salary,\n        DENSE_RANK() OVER (ORDER BY salary DESC) AS rank\n    FROM employees\n) ranked\nWHERE rank = 3;\n\n-- Method 2: LIMIT + OFFSET\nSELECT DISTINCT salary\nFROM employees\nORDER BY salary DESC\nLIMIT 1 OFFSET 2;`,
  },
  { id: 'p7', title: 'Fibonacci Series', difficulty: 'Easy', category: 'Recursion', language: 'python',
    description: 'Generate first N Fibonacci numbers.',
    examples: [{ input: 'n=7', output: '[0, 1, 1, 2, 3, 5, 8]' }],
    hint: 'Use iterative approach with two variables for O(n) time.',
    solution: `def fibonacci(n):\n    if n <= 0: return []\n    if n == 1: return [0]\n    fib = [0, 1]\n    for i in range(2, n):\n        fib.append(fib[-1] + fib[-2])\n    return fib`,
  },
  { id: 'p8', title: 'Binary Search', difficulty: 'Easy', category: 'Search', language: 'python',
    description: 'Implement binary search on a sorted array. Return index of target or -1.',
    examples: [{ input: 'arr=[1,3,5,7,9], target=5', output: '2' }],
    hint: 'Use left and right pointers, check mid element each iteration.',
    solution: `def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1`,
  },
  { id: 'p9', title: 'Employees Earning More Than Manager', difficulty: 'Medium', category: 'SQL', language: 'sql',
    description: 'Write SQL to find employees who earn more than their manager.',
    examples: [{ input: 'employees table with manager_id', output: 'Employee names with higher salary than manager' }],
    hint: 'Use self JOIN matching employee.manager_id = manager.id.',
    solution: `SELECT e.name AS employee, e.salary AS emp_salary,\n       m.name AS manager, m.salary AS mgr_salary\nFROM employees e\nJOIN employees m ON e.manager_id = m.id\nWHERE e.salary > m.salary;`,
  },
  { id: 'p10', title: 'Maximum Subarray Sum', difficulty: 'Medium', category: 'Array', language: 'python',
    description: "Find the contiguous subarray with the maximum sum (Kadane's Algorithm).",
    examples: [{ input: '[-2,1,-3,4,-1,2,1,-5,4]', output: '6 (subarray [4,-1,2,1])' }],
    hint: "Track current_sum and max_sum. Reset current_sum when it goes negative.",
    solution: `def max_subarray_sum(arr):\n    max_sum = current_sum = arr[0]\n    for num in arr[1:]:\n        current_sum = max(num, current_sum + num)\n        max_sum = max(max_sum, current_sum)\n    return max_sum`,
  },
  { id: 'p11', title: 'Balanced Parentheses', difficulty: 'Medium', category: 'Stack', language: 'python',
    description: 'Check if a string of brackets is balanced: (), {}, [].',
    examples: [{ input: '"({[]})"', output: 'True' }, { input: '"({[})"', output: 'False' }],
    hint: 'Use a stack. Push opening brackets, pop and match closing brackets.',
    solution: `def is_balanced(s):\n    stack = []\n    mapping = {')': '(', '}': '{', ']': '['}\n    for char in s:\n        if char in '({[':\n            stack.append(char)\n        elif char in ')}]':\n            if not stack or stack[-1] != mapping[char]:\n                return False\n            stack.pop()\n    return len(stack) == 0`,
  },
  { id: 'p12', title: 'Remove Duplicates from Sorted Array', difficulty: 'Easy', category: 'Array', language: 'python',
    description: 'Remove duplicates from a sorted array in-place and return the new length.',
    examples: [{ input: '[1,1,2,2,3]', output: '3 (array becomes [1,2,3,...])' }],
    hint: 'Use two pointers — slow and fast.',
    solution: `def remove_duplicates(arr):\n    if not arr: return 0\n    slow = 0\n    for fast in range(1, len(arr)):\n        if arr[fast] != arr[slow]:\n            slow += 1\n            arr[slow] = arr[fast]\n    return slow + 1`,
  },
]

export const SCENARIOS = [
  { id: 's1', title: 'Automation Suite Breaks After UI Redesign',
    category: 'Selenium',
    situation: 'Your company just deployed a major UI redesign. 60% of your Selenium automation tests are failing. The team needs regression results by tomorrow morning.',
    keyPoints: [
      'Prioritize: Run smoke tests first to identify scope of damage',
      'Analyze: Group failures by type (locator changes, flow changes, new elements)',
      'Fix strategy: Update locators using data-testid attributes, update page objects',
      'Prevention: Advocate for stable test IDs, use relative locators, implement self-healing',
      'Communication: Send status update to team with ETA and impact assessment',
    ],
  },
  { id: 's2', title: 'Flaky Tests Blocking CI Pipeline',
    category: 'CI/CD',
    situation: 'Your Jenkins pipeline has been red for 3 days due to intermittent test failures. The development team wants to disable all automation tests.',
    keyPoints: [
      'Investigate root causes: timing issues, test data, shared state, environment differences',
      'Quick fix: Add retry mechanism (TestNG IRetryAnalyzer) for immediate relief',
      'Quarantine: Move flaky tests to separate suite, unblock pipeline',
      'Fix systematically: Replace Thread.sleep with explicit waits, isolate test data',
      'Set SLA: Every quarantined test must be fixed within 1 sprint',
      'Track metrics: Dashboard showing flaky test rate (target < 2%)',
    ],
  },
  { id: 's3', title: 'API Returns 200 But Data Is Wrong',
    category: 'API Testing',
    situation: 'Your API automation tests pass (status 200) but QA found that the response data is incorrect. Users are seeing wrong order totals.',
    keyPoints: [
      'Root cause: Tests only validated status code, not response body values',
      'Immediate: Add response body assertions — validate specific field values',
      'Add JSON Schema validation to catch structural issues',
      'Implement data-driven testing with known expected values',
      'Add boundary testing: empty values, max values, special characters',
      'Lesson: Status code alone is NEVER sufficient for API validation',
    ],
  },
  { id: 's4', title: 'Production Bug Missed By Automation',
    category: 'Strategy',
    situation: 'A critical bug reached production. Management asks why automation didn\'t catch it. It turns out the scenario was never automated.',
    keyPoints: [
      'Acknowledge the gap without being defensive',
      'Analyze: Map the gap in test coverage using a traceability matrix',
      'Action plan: Prioritize automation of critical user journeys',
      'Implement risk-based testing — focus on high-impact, high-frequency scenarios',
      'Add the missing test immediately with regression suite',
      'Process improvement: Require automation story for every new feature user story',
    ],
  },
  { id: 's5', title: 'Need to Automate Without Stable Locators',
    category: 'Selenium',
    situation: 'The development team uses auto-generated class names (CSS modules) that change on every build. Your locators break constantly.',
    keyPoints: [
      'Advocate for data-testid attributes on critical elements',
      'Use text-based locators: getByText, getByRole (Playwright approach)',
      'Use relative XPath with stable parent elements',
      'Implement a locator strategy hierarchy: ID > data-testid > CSS > XPath',
      'Create a shared locator contract with the development team',
      'Consider visual testing as complement for layout validation',
    ],
  },
  { id: 's6', title: 'Test Environment Is Down Before Release',
    category: 'Strategy',
    situation: 'It\'s Friday, release is Monday. The staging environment has been down since Thursday. No automation tests have run.',
    keyPoints: [
      'Escalate immediately to DevOps/Infrastructure team',
      'Parallel action: Run API tests against available endpoints',
      'Prepare tests to run immediately when env is restored',
      'Risk assessment: Document what couldn\'t be tested and the risk',
      'Propose: Run smoke tests on production post-deploy with rollback plan',
      'Long-term: Push for environment monitoring and alerting',
    ],
  },
]

export const DAILY_GOAL_TEMPLATES = [
  { id: 'g1', text: 'Read 1 chapter completely', xp: 30 },
  { id: 'g2', text: 'Complete 1 quiz with 70%+ score', xp: 30 },
  { id: 'g3', text: 'Solve 3 coding problems', xp: 30 },
  { id: 'g4', text: 'Review 10 flashcard questions', xp: 30 },
  { id: 'g5', text: 'Practice 1 interview scenario aloud', xp: 30 },
  { id: 'g6', text: 'Write code for 2 SQL queries', xp: 30 },
]

export const MOTIVATIONAL_QUOTES = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "It's not about perfect. It's about effort.", author: "Jillian Michaels" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
  { text: "Testing leads to failure, and failure leads to understanding.", author: "Burt Rutan" },
  { text: "Every bug you find is a step toward mastery.", author: "SDET Wisdom" },
  { text: "You are one interview away from changing your life.", author: "Keep Grinding" },
]
